[profile.default]
solc = "0.8.21"
evm_version = "shanghai"
optimizer = true
optimizer_runs = 200


remappings = [
  "src/=src/",
  "forge-std/=lib/forge-std/src/",
  "lz/=lib/solidity-examples/contracts/",
]

[fmt]
number_underscore="thousands"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
